### ISSUE TITLE
Is there anyway to get an uppcase version of @BASENAME@?

### ISSUE THREAD

**Issue by TheKnarf** [noahfrederick/vim-skeleton#12]
Wanting to use this for C header files I'd like for BASENAME to be uppercased so that instead of getting the first example I could get the second one:

```
#ifndef test_H
#define test_H



#endif
```

```
#ifndef TEST_H
#define TEST_H



#endif
```

**Comment by noahfrederick** [comment]
Sure. See `:help g:skeleton_replacements`. You want to add something like this (untested) to your vimrc:

```vim
let g:skeleton_replacements_c = {}

function! g:skeleton_replacements_c.HEADER()
    return toupper(expand('%:t:r_H'))
endfunction
```

Or if you want it to work for all file types:

```vim
let g:skeleton_replacements = {}

function! g:skeleton_replacements.HEADER()
    return toupper(expand('%:t:r_H'))
endfunction
```

And then your template would be:

```c
#ifndef @HEADER@
#define @HEADER@



#endif
```

--------

By the way, I don't use this plug-in myself anymore. In case you aren't already aware of it, check out [Projectionist.vim](https://github.com/tpope/vim-projectionist). It covers your use case and more (e.g., flipping between header and implementation files with `:A`).

**Comment by TheKnarf** [comment]
I'll test that out!

---

Btw, I'm fairly happy with your plugin so far and don't feel the need to switch.
