### ISSUE TITLE
E116: Invalid arguments for function skeleton#ReadTemplate(g:skeleton_find_template[type]

### ISSUE THREAD

**Issue by AmarBattulga** [noahfrederick/vim-skeleton#8]
hi

I just installed vim-skeleton with NeoBundle but it keep says this message:

    Error detected while processing function <SNR>45_load_by_filetype..skeleton#Load:
    line    9:
    E116: Invalid arguments for function skeleton#ReadTemplate(g:skeleton_find_template[type](a:filename))
    E15: Invalid expression: ! exists('g:skeleton_find_template.'.type) || ! skeleton#ReadTemplate(g:skeleton_find_template[type](a:filename))
    Error detected while processing function <SNR>45_load_by_filename..skeleton#Load:
    line    9:
    E116: Invalid arguments for function skeleton#ReadTemplate(g:skeleton_find_template[type](a:filename))
    E15: Invalid expression: ! exists('g:skeleton_find_template.'.type) || ! skeleton#ReadTemplate(g:skeleton_find_template[type](a:filename))

**Comment by noahfrederick** [comment]
I just cut a release (v0.5.0) that fixes this issue.
