### ISSUE TITLE
No proper handling skeletons if skel.cpp file is present in templates directory

### ISSUE THREAD

**Issue by tymonx** [noahfrederick/vim-skeleton#9]
No proper handling skeletons if skel.cpp file is present in templates directory. Example directory contents:
skel.c  skel.cmake  skel.cpp  skel.h  skel.hpp  skel.md  skel.py  skel.txt  test.c

* Creating test.hpp load skel.cpp skeleton.
* Creating test.h load skel.cpp skeleton.

**Comment by noahfrederick** [comment]
Yes, the skeleton file that's read in is currently based on the buffer's `'filetype'` instead of the file extension. Thanks for pointing this out. I'll fix it.

**Comment by noahfrederick** [comment]
I just cut a release (v0.5.0) that fixes this issue.
